name: Run XCTest on GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies (if using CocoaPods)
        run: pod install || true

      - name: Build and Run XCTest
        run: |
          xcodebuild test \
          -workspace RedEyeAuto.xcworkspace \
          -scheme RedEyeAutoUITests \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          CODE_SIGNING_REQUIRED=NO
